language: node_js
node_js:
  - '10'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version
script:
  - yarn prettier --list-different '**/*.{js,json,md,ts,yml}'
  - yarn compile
  - yarn lint
